### ISSUE TITLE
job-time clasida margin qolib ketgan 

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [akramjonnuriddinov/001-joblistings#1]
![image](https://user-images.githubusercontent.com/99403792/167102817-def69242-ba52-4cd8-bcba-29b12ec6a316.png)
bunda not(:last-child) qilib berish kerak edi margin right ni

**Comment by akramjonnuriddinov** [comment]
Bu holatda qolsa ham zarari yo'q ekan.
