### ISSUE TITLE
company-name-link clasida margin qolib ketgan

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [akramjonnuriddinov/001-joblistings#2]
![image](https://user-images.githubusercontent.com/99403792/167103110-18b640fd-885f-4b1f-a131-0ea31de3ebd8.png)
bu xolatdaxam agar oxirgi element bolsa margin-right bolmasin deyish kerak edi

**Comment by akramjonnuriddinov** [comment]
Turaversayam zarari yo'q ekan
