### ISSUE TITLE
sayt kattalashtirilganda yozuvlar ikkinchi qatorga tushub ketyapti

### ISSUE THREAD

**Issue by Sardorbek-Raximberdiyev** [akramjonnuriddinov/001-joblistings#3]
![image](https://user-images.githubusercontent.com/99403792/167103609-7694e173-d9d8-4db6-a334-8726ad793045.png)
bu xolatda pastidagiga withe space nowrap berish kerak menimcha

**Comment by akramjonnuriddinov** [comment]
To'g'riladim.
